spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskfleet
    username: taskfleet
    password: taskfleet
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
