spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskfleet
    username: taskfleet
    password: taskfleet
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

aws:
  localstack:
    endpoint: http://localhost:4566
    region: us-east-1
  sqs:
    orderEventsQueue: taskfleet-order-events

consumer:
  pollDelayMs: 1000
  maxMessages: 5
  waitTimeSeconds: 10
